### ISSUE TITLE
0.9.5 update seems to be broken

### ISSUE THREAD

**Issue by hochgi** [scallop/scallop#91] opened 2014-09-21 11:46 UTC
Main class fails at initialization phase. this is the relevant stack trace:

```
Caused by: java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:313)
    at scala.None$.get(Option.scala:311)
    at org.rogach.scallop.ScallopOption.apply(ScallopOption.scala:28)
    at org.rogach.scallop.ScallopConfValidations$$anonfun$validate$2.apply(ScallopConfValidations.scala:28)
    at org.rogach.scallop.ScallopConfValidations$$anonfun$validate$2.apply(ScallopConfValidations.scala:27)
    at org.rogach.scallop.ScallopConf$$anonfun$runValidations$1.apply(ScallopConf.scala:285)
    at org.rogach.scallop.ScallopConf$$anonfun$runValidations$1.apply(ScallopConf.scala:284)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.rogach.scallop.ScallopConf.runValidations(ScallopConf.scala:284)
    at org.rogach.scallop.ScallopConf.verify(ScallopConf.scala:275)
    at org.rogach.scallop.ScallopConf.afterInit(ScallopConf.scala:504)
    at org.rogach.scallop.AfterInit$class.delayedInit(AfterInit.scala:14)
    at org.rogach.scallop.ScallopConf.delayedInit(ScallopConf.scala:26)
    at org.example.Main$Conf$.<init>(Main.scala:20)
    at org.example.Main$Conf$.<clinit>(Main.scala)
```

I'm using scala 2.10 (2.10.4). the Conf object is pretty standard.

**Comment by hochgi** [comment] 2014-09-21 18:15
forgot to mention, code worked fine in 0.9.4 and all previous versions. broke only when I tried to upgrade...

**Comment by Rogach** [comment] 2016-03-01 19:56
I'll close this issue as lots of time has passed and I am unable to reproduce this problem. If you still have this problem, please reopen the issue and give an example of a failing Conf object - currently, all tests pass, so I can only guess that there could be some issue with your config.

**Closed as completed by Rogach** 2016-03-01 19:56 UTC
