### ISSUE TITLE
Printing help when a required argument is missing

### ISSUE THREAD

**Issue by akisaarinen** [scallop/scallop#21] opened 2012-09-17 16:04 UTC
When defining a Scallop configuration using `ScallopConf`, how does one print the option help when a required argument is missing? `ScallopConf` seems to verify the validity of the given configuration (including the presence of required arguments) upon construction, so printing the help seems impossible.

**Comment by Rogach** [comment] 2012-09-17 16:13
I can add a callback, where you would be able to match on exceptions from the verification:

``` scala
object Conf extends ScallopConf(Nil) {
  guessOptionNames = true

  val apples = opt[Int](required = true)

  onError { 
    case RequiredOptionMissing(name) => 
      println("Required option missing: '%s'" format name)
      printHelp
  }
}
```

Would that be enough?

**Comment by Rogach** [comment] 2012-09-17 16:15
And actually, you can do almost that right now - just verify your configuration explicitly:

``` scala
object Conf extends ScallopConf(Nil) {
  val apples = opt[Int]("apples", required = true)
  try {
    verify
   } catch {
     case RequiredOptionMissing(_) =>
       builder.printHelp
       sys.exit(1)
   }
}
```

**Comment by akisaarinen** [comment] 2012-09-17 16:32
Ah, didn't figure out it is possible that way.

However, I don't particularly like this solution which `sys.exit`s in the configuration object upon its construction. I would like to have my `sys.exit`s in a single place, which is the main method of the application. Do you see any way of separating these concepts so that it would be possible?

**Comment by akisaarinen** [comment] 2012-09-17 16:44
The solution you suggested has one bug: if `--help` option is given, the help will be printed twice, because it is already printed once by Scallop before arriving to the catch block.

**Comment by akisaarinen** [comment] 2012-09-17 17:17
Right now I am using it with something like this:

``` scala
case class Conf(
  arguments: List[String],
  onHelp:    Scallop => Unit,
  onError:   (Scallop, Exception) => Unit
) extends ScallopConf(arguments) {
  val apples = opt[Int]("apples", required = true)

  try {
    if (builder.isSupplied("help")) {
      onHelp(builder)
    } else {
      verify
    }
  } catch {
    case e: Exception =>
      onError(builder, e)
  }
}
```

However, this is a bit ugly and I would like to see a cleaner API for getting control over the exits and errors to the application. What do you think?

**Comment by Rogach** [comment] 2012-09-17 17:31
For me, the following snippet prints help only once (since --help should exit the application immediately anyway):

``` scala
object Conf extends ScallopConf(Seq("--help")) {
  val apples = opt[Int]("apples", required = true)
  try {
    verify
  } catch {
    case e: exceptions.RequiredOptionNotFound =>
      println(builder.help)
      sys.exit(1)
  }
}
```

However, I do agree that it is more of a hack. 

About cleaner API - maybe something like following?

``` scala
object Conf extends ScallopConf(Nil) {
  guessOptionNames = true

  val apples = opt[Int](required = true)

  onError { 
    case RequiredOptionMissing(name) => 
      println("Required option missing: '%s'" format name)
      printHelp
    // other exceptions handling
  }

  onExit { // suspends exit, works only inside ScallopConf
    case Help =>
    case Exit =>
  }
}
```

And you would be able to inspect that errors even outside the conf object:

``` scala
object Main extends App {
  val conf = ...

  conf.onError { // executes immediately, right here. Consumes the error.
    case RequiredOptionMissing(name) =>
  }
}
```

What do you think?

**Comment by akisaarinen** [comment] 2012-09-17 17:46
Yes a cleaner API would be great.

The one you suggested seems OK for the error handling, but why would you want to keep the exit trapping only inside the configuration object? Couldn't we just allow that to be defined in App as well?

That would remove all hardcoded sys.exits from the framework and allow handling these cases as is best suited for the app. And then you could create convenience functions for the default use case so that the simple apps an just use the default exit and error handlers which print and sys.exit?

**Comment by Rogach** [comment] 2012-09-17 18:00
Well, you are right, but the problem is that verification and calling those functions is going to happen while ScallopConf is constructed - and at that moment, it has no way to know that somebody would handle errors afterwards.

Consider this scenario:

``` scala
object Main extends App {
  val conf = new ScallopConf(args) {
    val apples = opt[Int]("apples", required = true)
  }

  // and nobody handled the error...
}
```

Oh, I got the idea - and I even get to keep backwards compatibility! I'll add a key into ScallopConf, something like `keepErrors`. All users that haven't set it to `true` enjoy the original behavior, and if it is set to `true`, then they can handle errors on any point in the future:

``` scala
object Main extends App {
  val conf = new ScallopConf(args) {
    keepErrors = true
    val apples = opt[Int]("apples", required = true)
  }

  conf.onExit {
    case Help =>
    case Version => 
    // case Exit - superclass of Help and Version
  }

  conf.onError {
    // partial function to handle errors
    // unhandled errors are re-thrown
  }
}
```

How about this?

**Comment by akisaarinen** [comment] 2012-09-17 19:03
That looks like a reasonable API to me.

Some potential improvements came to mind, like combining `onExit` and `onError` to just one handler partial function, which handles all of the cases.

How about something like this (didn't try compiling this, though):

``` scala
sealed trait Result
object Result {
  case object Help extends Result
  case object Version extends Result
  case class Error(exception: ScallopException) extends Result
}

object Main extends App {
  val conf = new LazyScallopConf(args) {
    val apples = opt[Int]("apples", required = true)
  }.initialize {
    case Result.Help             => // --help given
    case Result.Version          => // --version given
    case Result.Error(exception) => // error during argument parsing
  }
  println("Apples: %d".format(conf.apples()))
}
```

Some ideas here are:
- `onExit` and `onError` are combined to one single `initialize` which takes in a partial function. All of the initialization results are extended from `Result`.
- I created a separate `LazyScallopConf` (a base class for `ScallopConf`), which requires calling `initialize`. This removes the need for `keepErrors` flag, and forces user to call `initialize`. You could implement some mechanism that prevents `LazyScallopConf` from working before being initialized. `ScallopConf` would then extend `LazyScallopConf` while calling `initialize` at the end of the constructor, with some default partial function implementation.

Does this make any sense to you? I don't know what would be the perfect design, but this could be implemented while being also backwards compatible, I think. And it would force the initialization.

And by the way, thanks for a very helpful attitude towards improving Scallop!

**Comment by Rogach** [comment] 2012-09-18 03:18
Looks good!

I'll probably implement it as you suggested, except I'd like to mess a little with Result hierarchy. I think something like this would be better:

``` scala
sealed trait Result
case object Help extends Result
case object Version extends Result
object Exit // matches both Help and Version
object Error // matches all errors
// + all exceptions
```

The only problem is that `Exit` and `Error` would require parentheses in match block, since otherwise they will only be checked for equality:

```
case Help =>
case Exit() =>
```

**Comment by Rogach** [comment] 2012-09-20 06:16
Proposed behavior is implemented in version `0.6.0`, which should be syncing to Central now.

Sorry for the delay - there were some issues with Sonatype repo.

**Comment by akisaarinen** [comment] 2012-09-20 08:17
Beautiful! 

I just took this into use and it allowed me to implement a very clean API. Just in case you're interested, I am currently using it like this, which means I have full control over `sys.exit`s at the application level (exactly what I wanted):

``` scala
import org.rogach.scallop.{ScallopConf, Scallop}
import org.rogach.scallop.exceptions.Help

class ExampleConfig(
  arguments: Array[String],
  onError:   (Throwable, Scallop) => Nothing
) extends ScallopConf(arguments) {
  val apple = opt[Int](
    name     = "apple",
    descr    = "Apple param",
    required = true
  )
  override protected def onError(e: Throwable) = onError(e, builder)
}

object TestApp extends App {
  val config = new ExampleConfig(args, onError)
  println("apple: %d".format(config.apple()))

  private def onError(e: Throwable, scallop: Scallop) = e match {
    case Help =>
      scallop.printHelp
      sys.exit(0)
    case _ =>
      println("Error: %s".format(e.getMessage))
      scallop.printHelp
      sys.exit(1)
  }
}
```

**Comment by Rogach** [comment] 2012-09-20 08:22
I'm glad it helped :)

Also, note that there exists a `summary` method on ScallopConf (and Scallop), so you don't need to write that formatting (`println("apple" format ...`):

``` scala
println(config.summary)
```

**Comment by akisaarinen** [comment] 2012-09-20 08:32
Yeah, great! 

By the way, I just noticed that you also added `LazyScallopConf` as we discussed, but I was not yet using it (just the `onError` handler). 

Using the `LazyScallopConf.initialize` is currently a bit more worksome than it could, because there is no access to the `Scallop` object from the partial function. I.e. you can't use `printHelp` & co without wrapping your config to a `val` first.

To use the lazy config in my app, I would like to do something like this:

``` scala
val config = new MyConfig(args).initialize(onError)

def onError(e: Throwable, scallop: Scallop) = e match {
  case Help => scallop.printHelp; sys.exit(0)
  case _ => [..]
}
```

Right now, that is possible but you have to do this:

``` scala
val config = new MyConfig(args)
config.initialize(onError(config.builder))

def onError(scallop: Scallop)(e: Throwable) = e match {
  case [..] => [..]
}
```

Do you think `initialize` could be made to work that way? It would drop the need for explicit `onError` wrapper in my config (which exists in the example I posted a few minutes ago).

**Comment by Rogach** [comment] 2012-09-20 08:41
Hm. You pointed out that I forgot to add `printHelp` method on ScallopConf :)

The idea was that builder should be hidden as much as possible, to protect programmer from some errors.

I think it would be better just to add missing methods to ScallopConf, so you would be able to do that like this:

``` scala
val config = new MyConfig(args)
config.initialize(onError _)

def onError(e: Throwable) = e match {
  case [..] => 
    config.printHelp
    [..]
}
```

As far I as I know, only `printHelp` method is missing on `ScallopConf`. Any others?

**Comment by Rogach** [comment] 2012-09-20 08:46
Added `.printHelp` (bc73c34).

**Comment by akisaarinen** [comment] 2012-09-20 08:48
Your suggested solution has a flaw: it assumes `config` is actually in scope of `onError`. In the small example that is the case (when extending from `App`). In my real code it's not, and I would not like to put `config` available to the  class scope. `config` is constructed within `def main()` and is not visible in `onError`.

In other words, this would still require me to do the following:

``` scala
val config = new MyConfig(args)
config.initialize(onError(config))

def onError(config: MyConfig)(e: Throwable) = [..]
```

The thing I don't like about this is that  I have to do the initialization as a separate statement. It would be cleaner to chain the `.initialize` and not have the non-initialized `config` available at any point. I would like to chain `.initialize`, which is not possible if I have to have the instance available at the point of creating the callback.

Does this make any sense?

**Comment by akisaarinen** [comment] 2012-09-20 08:50
And you have a point about hiding the builder, it should be `MyConfig` that's coming to the `onError` callback. So IMO the optimal API would look something like this:

``` scala
def someConstructingMethod {
  val config = new MyConfig(args).initialize(onError)
  print(config.summary)
}

def onError(config: MyConfig)(e: Throwable) = e match {
  case [..] => [..]
}
```

**Comment by Rogach** [comment] 2012-09-20 09:06
The problem is that I don't see a way to pass the config into the method, and that problem lies in the type system.

Basically, when you create new config using `new ScallopConf` or `extends ScallopConf`, the resulting value is not of type `ScallopCinf`, but of type `MyConfig extends ScallopConf`. And I just don't see a way to conveniently implement that `initialize` function in the form:

``` scala
def initialze(fn: (<ThisConfig>, Throwable) => Unit)
```

It could be possible (as we see from Scala Collections), but requires a lot of boilerplate (`CanBuildFrom`).

Besides, since .initialize neither creates new config nor mutates old one, it makes sense to have it as a separate statement - where you can combine it with just about anything.

So you can write it like this:

``` scala
def someConstructingMethod {
  val config = new MyConfig(args)
  config.initialize(onError(config))
  print(config.summary)
}

def onError(config: MyConfig)(e: Throwable) = e match { ... }
```

And this is just one small step from your optimal goal :)

**Comment by Rogach** [comment] 2012-09-20 09:08
I could write that `intialize` as

``` scala
def intialize(fn: (ScallopConf, Throwable) => Unit)
```

but this way you would not be able to inspect options on passed config, and it seems to be too clumsy to put it as a standard way to deal with exceptions.

**Comment by akisaarinen** [comment] 2012-09-20 09:34
Ah, type system limitations... :)

Passing the correctly typed configuration class to `initialize` does indeed seem tricky... I'll let you know if I come up with anything clever, but for now I think this is good enough. Thanks!

**Comment by Rogach** [comment] 2012-09-20 11:33
Ok. I'll close this issue for now, if you find something interesting, just reopen it.

Thanks for your suggestions!

**Closed as completed by Rogach** 2012-09-20 11:33 UTC
Labels: enhancement
